apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dhinojosa/prometheus-grafana.git
    targetRevision: main
    path: demos/canary-app/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: canary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
