apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
  namespace: canary
  labels:
    app: quarkus-app
spec:
  selector:
    app: quarkus-app
  ports:
    - name: http
      port: 8081
      targetPort: http
