quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=coffee
quarkus.datasource.password=coffee
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/coffee

quarkus.hibernate-orm.database.generation=update

quarkus.jackson.write-dates-as-timestamps=false
